


[functions.whatsapp-webhook]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-whatsapp-webhook]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.aisensy-templates]
verify_jwt = false

[functions.today_words]
verify_jwt = false


